[package]
name = "features"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
domain.workspace = true
rust_decimal.workspace = true
chrono.workspace = true

[dev-dependencies]
rust_decimal_macros.workspace = true
uuid.workspace = true
